#!/bin/bash

set -ex

mkdir -p build

rm -rf build/*
rm -f yagg.zip

cp frontend/*.* build/
cp -r frontend/icons build/

tsc
cp -r frontend/js build

mkdir -p build/img/howto

# delete metadata
exiftool -All= -r -overwrite_original_in_place frontend/img/*.png

# optimize images
while IFS= read -r -d $'\0' path; do
  cat "frontend/img/${path}" | pngquant - > "build/img/${path}"
done < <(cd frontend/img && find . -name "*.png" -print0)

( cd build && zip -r ../yagg ./* )
